###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '25001:8025'

    redis:
        image: 'redis:alpine'

    mariadb:
        image: 'mariadb:11.0'
        working_dir: /application
        volumes:
            - './estudos:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=senha
            - MYSQL_DATABASE=mariadb
            - MYSQL_USER=usuario
            - MYSQL_PASSWORD=senha2
        ports:
            - '25003:3306'

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - './estudos:/application'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=senha
            - POSTGRES_DB=postgres
        ports:
            - '25004:5432'

    elasticsearch:
        image: 'elasticsearch:6.5.4'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './estudos:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '25000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './estudos:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
